# Generated by Django 3.2.3 on 2022-02-28 00:48

import api_notification.models_validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[api_notification.models_validator.mobile_phone_validator])),
                ('timezone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MallingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_notification_date', models.DateTimeField(verbose_name='Дата начала рассылки')),
                ('end_notification_date', models.DateTimeField(verbose_name='Дата завершения рассылки')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MobileOperatorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код оператора')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(null=True, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('SEND', 'Send'), ('ERROR', 'Error'), ('NEW', 'New')], max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api_notification.client')),
                ('malling_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api_notification.mallinglist')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_operator_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='api_notification.mobileoperatorcode', verbose_name='Код оператора'),
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='api_notification.tag', verbose_name='Тег'),
        ),
    ]
