# Generated by Django 3.2.3 on 2022-02-28 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='mallinglist',
            table='malling_list',
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
        migrations.AlterModelTable(
            name='mobileoperatorcode',
            table='mobile_operator_code',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
